### PR TITLE
Additional extraction handling 

### PR DESCRIPTION
**Pull request by dign17**
Hello Kees,

I added extraction handling for embedded documents containing "%DocumentOle:" delimited header and some unit tests. This is important for pdf documents attached in MSOffice where an OLE component is registered by the installed pdf reader.

With kind regards

### CODE REVIEW

**Comment by Sicos1977** [comment]
Looks good... merged... thanks for building

**Comment by Sicos1977** [comment]
I just released a new version (1.6.0) to NuGet

**Comment by dign17** [comment]
Thanks

**Comment by dign17** [comment]
I am using it to extract embedded files within a product which converts documents and images to PDF.

**Comment by Sicos1977** [comment]
Nice... that is exactly the same what I do :-)

**Comment by harg** [comment]
@Sicos1977 which library do you use to convert to pdf? (I need one supporting pdf/a)

**Comment by Sicos1977** [comment]
What kind of documents do you need to convert? For office document I just use office --> https://github.com/Sicos1977/OfficeConverter and for HTML document I use --> https://github.com/Sicos1977/ChromeHtmlToPdf

I build a software package that can convert about 200 different file types, but I can't share that on GitHub because that is build in working hours so that belongs to the company where I'm working. All the different components on GitHub are build in my own time so with that you can do what you want.

**Pull request merged**
