### PR TITLE
Ignore Microsoft ClipArt Gallery objects

### PR DESCRIPTION
**Pull request by bormm**
We again had some files containing "special" objects. In this case used for Microsoft ClipArt Gallery objects. Extracting them seems again impossible and/or unnecessary, the image is full visible within PowerPoint.

I also removed the .vs folder, containing visual studio tmp files, from the repo again.

Please discuss or merge if ok and create a new release.

Thank you!

### CODE REVIEW

**Comment by bormm** [comment]
@Sicos1977 Hi Kees, can you estimate when the new nuget package will be released?

**Comment by Sicos1977** [comment]
I'll try to make a new nuget package this evening

**Comment by Sicos1977** [comment]
I just released a new NuGet package

**Comment by bormm** [comment]
Hi Kees. I updated to the 1.6.3 nuget package, but the changes are not included. 
They are within the source package on github, but not within the nuget package.
I decompiled this:
2018-07-24_16h52_29

**Comment by Sicos1977** [comment]
I don't know what exactly did go wrong but I published the package again but now as a 1.6.4 version

**Pull request merged**
